### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by xuyunlu1030** [piergiaj/super-events-cvpr18#2]
when evaluating the provided model, using:
rgb_model = torch.load(args.rgb_model_file)
rgb_model.cuda()

only the two baseline model can run successfully.
It looks that the input model should be in type of <class 'torch.nn.modules.container.Sequential'> like (rgb_baseline or flow_baseline), while others are in type of <class 'collections.OrderedDict'>.
Can you help me solve the problem? Thanks.

**Comment by piergiaj** [comment]
The OrderedDict type needs 
```rgb_model.load_state_dict(torch.load(model_file))```

I thought I made them all the same format, but may have missed some. I will check soon. Until then, some will need load_state_dict and others can be just torch.load().

**Comment by Juruobudong** [comment]
I also only the two baseline model can run successfully.
when I use
python train_model.py -mode joint -train False -rgb_model_file models/charades/cvpr_charades_rgb_final -flow_model_file models/charades/cvpr_charades_flow_final

and change code
            rgb_model = super_event.get_super_event_model(0, classes)
            rgb_model = rgb_model.load_state_dict(torch.load(args.rgb_model_file))
then error is 
  File "train_model.py", line 251, in <module>
    rgb_model = rgb_model.load_state_dict(torch.load(args.rgb_model_file))
  File "/gpfs/home/lhe/anaconda3/envs/xxw_py2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 490, in load_state_dict
    .format(name))
KeyError: 'unexpected key "module.cls_wts" in state_dict'
