### ISSUE TITLE
RuntimeError: invalid argument 7: expected 3D tensor

### ISSUE THREAD

**Issue by lwq1122** [piergiaj/super-events-cvpr18#3]
Hi, I found some errors when I run train_model.py and I got this error in super-event.py, and I use pytorch-i3d to extract features first:

Traceback (most recent call last):
  File "train_model.py", line 260, in <module>
    rgb_results = eval_model(rgb_model, dataloaders['val'], baseline=False)
  File "train_model.py", line 123, in eval_model
    outputs, loss, probs, _ = run_network(model, data, 0, baseline)
  File "train_model.py", line 142, in run_network
    outputs = model([inputs, torch.sum(mask, 1)])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/super-events-cvpr18/super_event.py", line 55, in forward
    super_event = torch.bmm(cls_wts.expand(inp[0].size()[0], -1, -1), super_event)
RuntimeError: invalid argument 7: expected 3D tensor at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:457

According to comment, I know we want change super-event(B×2×D*3) to super-event(B×C×D*3)
But I print 'cls_wts.expand(inp[0].size()[0], -1, -1)' ,it's a 3D Tensor((1L, 157L, 2L)), super-event is a 4D Tensor((1L, 2L, 1024L, 3L)). They can't do torch.bmm()

Can you help me fix this error?  Thank you so much!!

**Comment by piergiaj** [comment]
I am not sure what is causing this error. The code runs fine for me and several others who have used it. Here are 2 suggestions to try:

1) Make sure you are using pytorch 0.3. Newer versions may cause errors.
2) Make sure your batch size >1, a batch size of 1 could cause problems particularly with the squeeze function.

**Comment by lwq1122** [comment]
Thank you very much
