### ISSUE TITLE
I also encountered this error,Is this problem related to the fps of the video?

### ISSUE THREAD

**Issue by lxhlxh130** [piergiaj/super-events-cvpr18#4]
1) Make sure you are using pytorch 0.3. Newer versions may cause errors.
2) Make sure your batch size >1, a batch size of 1 could cause problems particularly with the squeeze function.

_Originally posted by @piergiaj in https://github.com/piergiaj/super-events-cvpr18/issues/3#issuecomment-421789866_

1. Sorry,  I use the provided cvpr_charades_rgb_final and cvpr_charades_flow_final, and I use pytorch 0.3 and set the batchsize=16, but also encountered this error,"RuntimeError: invalid argument 7: expected 3D tensor at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:457"

And I use the provided rgb and flow frames(fps=24) at Charades website, so, is this problem related to fps or it is caused by the feature extraction step ?
2. After I extracted features use pytorch-i3d, I only got two-stream MAP: 0.0773211746124 without any error. I don't know which step I made wrong. Is this result normal?

**Comment by piergiaj** [comment]
I changed the code so it should fix this 3D tensor error. I'm not sure what is going wrong for you, but this update should hopefully fix it.

**Comment by lxhlxh130** [comment]
Thank you so much, I have tried this and it runs successfully.
