### ISSUE TITLE
Temporal resolution of results

### ISSUE THREAD

**Issue by gurkirt** [piergiaj/super-events-cvpr18#7]
Thank you very much for making the code available online. It's been really helpful. 

May I ask, what is the temporal resolution of output predictions. Do you produce `C` dimensional sigmoid activations or every 8 frames, same as I3D temporal resolution? I3D compress 8 frames into one feature vector or classification vector, 16 into 2, 32 into 4, 64 into 8, and so on. Given 64 RGB frames, do you produce 8 score vectors or 64?

Thanks- gurkirt

**Comment by piergiaj** [comment]
We followed the I3D setting from the Charades competition and took the output, interpolated it to match the input size then sampled 25 evenly spaced frames which were used as the input to the evaluation script. We also tried without the interpolation and just taking 25 outputs directly from the I3D features and it did not make any noticeable difference.
